name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black mypy PyQt6 requests
      - name: Ruff
        run: ruff check .
      - name: Black (check)
        run: black --check .
      - name: Mypy (non-strict)
        run: mypy --ignore-missing-imports --follow-untyped-imports . || true